In [1]:
import lseg.data as ld
import pandas as pd
from dataquery import *
import os
app_key = os.environ['APP_KEY']
ld.open_session(app_key=app_key)

We get all global vars and methods from dataquery into this namespace, so we do not need to write code like dataquery.SCREEN, etc.

The below cell shows, how the user can create the screener query in 1 line of code via the "express" class:

In [2]:
screen = SCREEN.express.universe(Equity(active=True, public=True, primary=True)) \
                .conditions(IN('TR.CoRTradingCountryCode', 'US'), TOP('TR.CompanyMarketCap', 10, nnumber)) \
                .currency('USD').query

screen

'SCREEN(U(IN(Equity(primary,public,active))),IN(TR.CoRTradingCountryCode,US),TOP(TR.CompanyMarketCap,10,nnumber),CURN=USD)'

The user can also get & set the parameters like universe, conditions, currency by setting them as properties directly in the SCREEN class:

In [3]:
SCREEN.universe

'Equity(primary,public,active)'

In [4]:
SCREEN.query

'SCREEN(U(IN(Equity(primary,public,active))),IN(TR.CoRTradingCountryCode,US),TOP(TR.CompanyMarketCap,10,nnumber),CURN=USD)'

<br>
<br>
We can now use the SCREEN statement in the get_data method with LSEG Data Library for Python:

In [5]:
df = ld.get_data(screen, ['TR.CompanyMarketCap'])
df

C:\Python312\Lib\site-packages\pandas\core\dtypes\cast.py:1056:RuntimeWarning: invalid value encountered in cast
C:\Python312\Lib\site-packages\pandas\core\dtypes\cast.py:1080:RuntimeWarning: invalid value encountered in cast

  Instrument    Company Market Cap
0    AAPL.OQ       3204508612360.0
1    MSFT.OQ       3162416042769.0
2    NVDA.OQ       2723284000000.0
3    AMZN.OQ  2018471632229.399902
4   GOOGL.OQ       1965509410000.0
5    META.OQ  1444515278722.129883
6     BRKa.N  1143913783166.969971
7    AVGO.OQ   927835540325.609985
8    TSLA.OQ   903542636309.719971
9      WMT.N    779366394000.51001

Here is another query example:

In [6]:
screen2 = SCREEN.express \
            .universe('0#.SPX') \
            .conditions(IN('TR.TRBCEconomicSector', 'Technology')) \
            .currency('USD').query

Let's add the ADC function "Rel" to pull the relative performance of the filtered S&P 500 stocks vs Apple:

In [7]:
df2 = ld.get_data(screen2, ['TR.EpsSmartEst', REL('AAPL.O','TR.EpsSmartEst')])
df2

   Instrument  Earnings Per Share - SmartEstimate®  REL(AAPL.O,TR.EPSSMARTEST)
0       ON.OQ                              2.40625                    0.337214
1     SMCI.OQ                              2.47017                    0.346172
2      AMD.OQ                              3.98007                    0.557771
3      WDC.OQ                              4.82227                    0.675798
4     ZBRA.OQ                             14.54858                    2.038853
..        ...                                  ...                         ...
93      FIS.N                              5.74832                    0.805575
94      ACN.N                             12.69934                    1.779698
95    CRWD.OQ                              3.40877                    0.477708
96    PANW.OQ                              3.22775                     0.45234
97    SNPS.OQ                             14.92714                    2.091904

[98 rows x 3 columns]

We can also specify the screener to look into M&A deals:

In [8]:
screen3 = SCREEN.express.universe(DEALS).conditions(IN('TR.MnAStatus', 'C'), RELATIVEDATE('TR.MnARelatedAnnDate', 'LM')).currency('USD').query

In [9]:
df3 = ld.get_data(screen3, ['TR.MNASDCDealNumber', 'TR.MnARelatedAcquiror', 'TR.MnADealValue'])
df3

C:\Python312\Lib\site-packages\lseg\data\_tools\_dataframe.py:192:FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
C:\Python312\Lib\site-packages\pandas\core\dtypes\cast.py:1056:RuntimeWarning: invalid value encountered in cast
C:\Python312\Lib\site-packages\pandas\core\dtypes\cast.py:1080:RuntimeWarning: invalid value encountered in cast

       Instrument SDC Deal No Related M&A Deal Acquiror  Deal Value
0     34392036819  2312653040             Seeking Buyer        <NA>
1     34392036819                         Seeking Buyer        <NA>
2     34392036819                            Ovomir OOO        <NA>
3     34392036823  2312657040             Seeking Buyer  1250000000
4     34392036823                         Seeking Buyer        <NA>
..            ...         ...                       ...         ...
308  154088887942  4392161040            Investor Group        <NA>
309  154088887967  4392165020            Investor Group        <NA>
310  154088887972  4392168020            Investor Group        <NA>
311  154088888450  4392342020             Gainsight Inc        <NA>
312  154088888453  4392344020             Gainsight Inc        <NA>

[313 rows x 4 columns]

The rest of this file contains more examples:

In [10]:
screen4 = SCREEN.express.universe('0#.SPX').conditions(TOP('TR.CompanyMarketCap', 10, nnumber)).currency('USD').query

In [11]:
df4 = ld.get_data(screen4, ['TR.PriceClose', ROUND(FORMULA('TR.PriceClose', '*2'),0)])
df4

  Instrument  Price Close  ROUND(TR.PRICECLOSE*2,0)
0    AAPL.OQ       213.32                       427
1    MSFT.OQ        425.4                       851
2    NVDA.OQ       111.61                       223
3    AMZN.OQ        190.2                       380
4   GOOGL.OQ        161.3                       323
5    GOOG.OQ       162.79                       326
6    META.OQ       572.21                      1144
7     BRKb.N       530.23                      1060
8    AVGO.OQ       197.33                       395
9    TSLA.OQ       280.52                       561